-- call generate token
DECLARE
    L_TIMESTAMP VARCHAR2 (200);
    L_SIGNATURE VARCHAR2 (1000);
    L_RAY_ID    VARCHAR2 (20);
    L_TOKEN     VARCHAR2 (4000);
BEGIN
    L_TIMESTAMP := TO_CHAR (SYSTIMESTAMP, 'rrrr-mm-dd') 
                        || 'T'
                        || TO_CHAR (SYSTIMESTAMP, 'hh24:mi:ssTZR');

    L_SIGNATURE := DEV.BJKT_JAVA_PKG.HASH256( P_INPUT => 'APEX|' || L_TIMESTAMP);
    L_RAY_ID := BJKT_JAVA_PKG.GET_RAY_ID();
    L_TOKEN := BJKT_SSO_INTEGRATIONS_PKG.GET_ACCESS_TOKEN(L_TIMESTAMP);

    DBMS_OUTPUT.PUT_LINE('TIMESTAMP: '  || L_TIMESTAMP);
    DBMS_OUTPUT.PUT_LINE('SIGNATURE: '  || L_SIGNATURE);
    DBMS_OUTPUT.PUT_LINE('RAY ID: '     || L_RAY_ID);
    DBMS_OUTPUT.PUT_LINE('TOKEN: '      || L_TOKEN);
END;
/

-- call get master data divisions
DECLARE
    L_STATUS    VARCHAR2(100);
    L_MESSAGE   VARCHAR2(1000);
BEGIN
    BJKT_SSO_INTEGRATIONS_PKG.GET_DIVISIONS (
        R_STATUS    => L_STATUS,
        R_MESSAGE   => L_MESSAGE
    );

    DBMS_OUTPUT.PUT_LINE('STATUS: ' || L_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE: ' || L_MESSAGE);
END;
/

-- call get master data departments
DECLARE
    L_STATUS    VARCHAR2(100);
    L_MESSAGE   VARCHAR2(1000);
BEGIN
    BJKT_SSO_INTEGRATIONS_PKG.GET_DEPARTMENTS (
        R_STATUS    => L_STATUS,
        R_MESSAGE   => L_MESSAGE
    );

    DBMS_OUTPUT.PUT_LINE('STATUS: ' || L_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE: ' || L_MESSAGE);
END;
/

-- call get master data levels
DECLARE
    L_STATUS    VARCHAR2(100);
    L_MESSAGE   VARCHAR2(1000);
BEGIN
    BJKT_SSO_INTEGRATIONS_PKG.GET_LEVELS (
        R_STATUS    => L_STATUS,
        R_MESSAGE   => L_MESSAGE
    );

    DBMS_OUTPUT.PUT_LINE('STATUS: ' || L_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE: ' || L_MESSAGE);
END;
/

-- call get master data departments
DECLARE
    L_STATUS    VARCHAR2(100);
    L_MESSAGE   VARCHAR2(1000);
BEGIN
    BJKT_SSO_INTEGRATIONS_PKG.GET_POSITIONS (
        R_STATUS    => L_STATUS,
        R_MESSAGE   => L_MESSAGE
    );

    DBMS_OUTPUT.PUT_LINE('STATUS: ' || L_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE: ' || L_MESSAGE);
END;
/

-- call get master data work units
DECLARE
    L_STATUS    VARCHAR2(100);
    L_MESSAGE   VARCHAR2(1000);
BEGIN
    BJKT_SSO_INTEGRATIONS_PKG.GET_WORK_UNITS (
        R_STATUS    => L_STATUS,
        R_MESSAGE   => L_MESSAGE
    );

    DBMS_OUTPUT.PUT_LINE('STATUS: ' || L_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE: ' || L_MESSAGE);
END;
/

-- call get master data work units
DECLARE
    L_STATUS    VARCHAR2(100);
    L_MESSAGE   VARCHAR2(1000);
BEGIN
    BJKT_SSO_INTEGRATIONS_PKG.GET_MODEL_WORK_UNITS (
        R_STATUS    => L_STATUS,
        R_MESSAGE   => L_MESSAGE
    );

    DBMS_OUTPUT.PUT_LINE('STATUS: ' || L_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE: ' || L_MESSAGE);
END;
/