/*
    -- START --
    CREATE TABLE TO STORE CREDENTIAL
*/
-- DROP TABLE BJKT_FND_CREDENTIAL;
-- /

CREATE TABLE BJKT_FND_CREDENTIAL (
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(200),
    URL VARCHAR2(200),
    VERSION VARCHAR2(10),

    CREDENTIAL_STATIC_ID VARCHAR2(255),
    CHANNEL_ID VARCHAR2(100),
    USER_NAME VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    WALLET_PATH VARCHAR2(100),
    WALLET_PASSWORD VARCHAR2(100),

    CLIENT_ID VARCHAR2(4000),
    CLIENT_KEY VARCHAR2(4000),
    PUBLIC_KEY VARCHAR2(4000),
    PRIVATE_KEY VARCHAR2(4000),
    SECRET_KEY VARCHAR2(4000),
    API_KEY VARCHAR2(4000),
    API_SECRET VARCHAR2(4000),

    CREATED_BY VARCHAR2(100),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_LOGIN NUMBER,
    LAST_UPDATED_BY VARCHAR2(100),
    LAST_UPDATE_DATE TIMESTAMP,

    CONSTRAINT BJKT_FND_CREDENTIAL_PK PRIMARY KEY (ID)
);
/

-- DROP SEQUENCE BJKT_FND_CREDENTIAL_S;
-- /

CREATE SEQUENCE BJKT_FND_CREDENTIAL_S
START WITH 1
INCREMENT BY 1;
/

-- DROP TRIGGER BJKT_FND_CREDENTIAL_TRG;
-- /

CREATE OR REPLACE TRIGGER DEV.BJKT_FND_CREDENTIAL_TRG
BEFORE INSERT OR UPDATE
ON DEV.BJKT_FND_CREDENTIAL
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, DEV.BJKT_FND_CREDENTIAL_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;

/
/*
    -- END --
    CREATE TABLE TO STORE CREDENTIAL
*/

/*
    -- START --
    CREATE TABLE TO STORE LOG API
*/
-- DROP TABLE BJKT_API_LOG;
-- /

CREATE TABLE BJKT_API_LOG (
    LOG_ID VARCHAR2(300) 
        DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'DDMMYYYYHH24MISSFF3')
        NOT NULL,

    NAME VARCHAR2(300),
    URL VARCHAR2(1000),
    ACCESS_TOKEN VARCHAR2(1000),
    CONTENT_TYPE VARCHAR2(1000),
    AUTHORIZATION VARCHAR2(1000),
    PARTNER_ID VARCHAR2(1000),
    TIME_STAMP VARCHAR2(1000),
    SIGNATURE VARCHAR2(1000),
    EXTERNAL_ID VARCHAR2(1000),
    CHANNEL_ID VARCHAR2(1000),
    RAY_ID VARCHAR2(20),

    HEADER CLOB,
    REQUEST CLOB,
    RESPONSE CLOB,

    ATTRIBUTE_CATEGORY VARCHAR2(150),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    ATTRIBUTE6 VARCHAR2(150),
    ATTRIBUTE7 VARCHAR2(150),
    ATTRIBUTE8 VARCHAR2(150),
    ATTRIBUTE9 VARCHAR2(150),
    ATTRIBUTE10 VARCHAR2(150),
    ATTRIBUTE11 VARCHAR2(150),
    ATTRIBUTE12 VARCHAR2(150),
    ATTRIBUTE13 VARCHAR2(150),
    ATTRIBUTE14 VARCHAR2(150),
    ATTRIBUTE15 VARCHAR2(150),

    IFACE_MODE VARCHAR2(30),
    IFACE_CODE NUMBER,
    IFACE_STATUS VARCHAR2(100),
    IFACE_MESSAGE VARCHAR2(4000),

    CREATED_BY VARCHAR2(100),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_LOGIN NUMBER,
    LAST_UPDATED_BY VARCHAR2(100),
    LAST_UPDATE_DATE TIMESTAMP,

    CONSTRAINT BJKT_API_LOG_PK PRIMARY KEY (LOG_ID)
);
/

-- DROP TRIGGER BJKT_API_LOG_TRG;
-- /

CREATE OR REPLACE TRIGGER BJKT_API_LOG_TRG
BEFORE INSERT OR UPDATE
ON BJKT_API_LOG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSDATE;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSDATE;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE LOG API
*/

/*
    -- START --
    CREATE TABLE TO STORE TOKEN
*/

-- DROP TABLE BJKT_ACCESS_TOKEN;
-- /

CREATE TABLE BJKT_ACCESS_TOKEN (
    ID                  NUMBER NOT NULL,
    NAME                VARCHAR2(200),
    ACCESS_TOKEN        VARCHAR2(4000),
    TIMESTAMP_TOKEN     VARCHAR2(200),
    EXPIRED_IN          NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_ACCESS_TOKEN_PK PRIMARY KEY (ID)
);
/

CREATE SEQUENCE BJKT_ACCESS_TOKEN_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_ACCESS_TOKEN_TRG
BEFORE INSERT OR UPDATE
ON BJKT_ACCESS_TOKEN
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_ACCESS_TOKEN_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE TOKEN
*/

/*
    -- START --
    CREATE TABLE TO STORE MASTER DIVISION
*/
-- DROP TABLE BJKT_DIVISIONS;
-- /

CREATE TABLE BJKT_DIVISIONS (
    ID                  NUMBER NOT NULL,
    DIVISION_ID         NUMBER NOT NULL,
    DIVISION_NAME       VARCHAR2(1000) NOT NULL,
    STATUS_DATA         NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_DIVISIONS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_DIVISIONS_U1 UNIQUE (DIVISION_ID)
    
);
/

CREATE OR REPLACE TRIGGER BJKT_DIVISIONS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_DIVISIONS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE MASTER DIVISION
*/

/*
    -- START --
    CREATE TABLE TO STORE WORK UNITS
*/
-- DROP TABLE BJKT_WORK_UNITS;
-- /

CREATE TABLE BJKT_WORK_UNITS (
    ID                  NUMBER NOT NULL,
    WORK_UNIT_ID        NUMBER NOT NULL,          
    WORK_UNIT_NAME      VARCHAR2(4000) NOT NULL,
    PARENT_BRANCH_CODE  VARCHAR2(200) NOT NULL,
    BRANCH_CODE         VARCHAR2(200) NOT NULL,
    WORK_UNIT_CATEGORY  VARCHAR2(200) NOT NULL,
    STATUS_DATA         NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_WORK_UNITS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_WORK_UNITS_U1 UNIQUE (WORK_UNIT_ID)
);
/

CREATE OR REPLACE TRIGGER BJKT_WORK_UNITS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_WORK_UNITS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE MASTER WORK UNITS
*/

/*
    -- START --
    CREATE TABLE TO STORE DEPARTMENTS
*/
-- DROP TABLE BJKT_DEPARTMENTS;
-- /

CREATE TABLE BJKT_DEPARTMENTS (
    ID                  NUMBER NOT NULL,
    DEPARTMENT_ID       NUMBER NOT NULL,          
    DEPARTMENT_NAME     VARCHAR2(4000) NOT NULL,
    STATUS_DATA         NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_DEPARTMENTS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_DEPARTMENTS_U1 UNIQUE (DEPARTMENT_ID)
);
/

CREATE OR REPLACE TRIGGER BJKT_DEPARTMENTS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_DEPARTMENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE MASTER DEPARTMENTS
*/

/*
    -- START --
    CREATE TABLE TO STORE POSITIONS
*/
-- DROP TABLE BJKT_POSITIONS;
-- /

CREATE TABLE BJKT_POSITIONS (
    ID                  NUMBER NOT NULL,
    POSITIONS_ID        NUMBER NOT NULL,          
    POSITIONS_NAME      VARCHAR2(4000) NOT NULL,
    STATUS_DATA         NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_POSITIONS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_POSITIONS_U1 UNIQUE (POSITIONS_ID)
);
/

CREATE OR REPLACE TRIGGER BJKT_POSITIONS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_POSITIONS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE MASTER POSITIONS
*/

/*
    -- START --
    CREATE TABLE TO STORE LEVELS
*/
-- DROP TABLE BJKT_LEVELS;
-- /

CREATE TABLE BJKT_LEVELS (
    ID                  NUMBER NOT NULL,
    LEVEL_ID            NUMBER NOT NULL,          
    LEVEL_NAME          VARCHAR2(4000) NOT NULL,
    STATUS_DATA         NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_LEVELS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_LEVELS_U1 UNIQUE (LEVEL_ID)
);
/

CREATE OR REPLACE TRIGGER BJKT_LEVELS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_LEVELS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE MASTER LEVELS
*/

/*
    -- START --
    CREATE TABLE TO STORE MASTER MODEL WORK UNITS
*/
-- DROP TABLE BJKT_MODEL_WORK_UNITS;
-- /

CREATE TABLE BJKT_MODEL_WORK_UNITS (
    ID                  NUMBER NOT NULL,
    MODEL_ID            NUMBER NOT NULL,          
    MODEL_NAME          VARCHAR2(4000) NOT NULL,
    STATUS_DATA         NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_MODEL_WORK_UNITS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_MODEL_WORK_UNITS_U1 UNIQUE (MODEL_ID)
);
/

CREATE OR REPLACE TRIGGER MODEL_WORK_UNITS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_MODEL_WORK_UNITS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE MASTER MODEL WORK UNITS
*/