select * from BJKT_UPLOAD_BANSOS order by id desc;
/
select * from BJKT_FILE_UPLOAD_LOG order by id desc;
/
select * from BJKT_BANSOS_RECIPIENTS_STG order by id desc;
/
select * from BJKT_HISTORY_BANSOS_RECIPIENTS order by id desc;
/
select * from BJKT_BANSOS_RECIPIENTS_ERR order by id desc;
/
select * from BJKT_CAL_BANSOS_RECIPIENTS_V;
/

delete from BJKT_BANSOS_RECIPIENTS_STG;
/
delete from BJKT_BANSOS_RECIPIENTS_ERR;
/
delete from BJKT_UPLOAD_BANSOS;
/
delete from BJKT_FILE_UPLOAD_LOG;
/
delete from BJKT_HISTORY_BANSOS_RECIPIENTS;
/
commit;
/

ALTER TABLE BJKT_BANSOS_RECIPIENTS_STG 
    DROP CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_C1;
/
ALTER TABLE BJKT_BANSOS_RECIPIENTS_STG 
    ADD CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_C1 
    CHECK (STATUS IN ('PENDING','VALID','ERROR','LOADED','SKIPPED'));
/
ALTER TABLE BJKT_UPLOAD_BANSOS ADD (
    SKIPPED_ROWS  NUMBER DEFAULT 0
);
/