select * from BJKT_UPLOAD_BANSOS order by id desc;
/
select * from BJKT_FILE_UPLOAD_LOG order by id desc;
/
select * from BJKT_BANSOS_RECIPIENTS_STG order by id desc;
/
select * from BJKT_HISTORY_BANSOS_RECIPIENTS order by id desc;
/
select * from BJKT_BANSOS_RECIPIENTS_ERR order by id desc;
/
select * from BJKT_CAL_BANSOS_RECIPIENTS_V;
/

delete from BJKT_BANSOS_RECIPIENTS_STG;
/
delete from BJKT_BANSOS_RECIPIENTS_ERR;
/
delete from BJKT_UPLOAD_BANSOS;
/
delete from BJKT_FILE_UPLOAD_LOG;
/
delete from BJKT_HISTORY_BANSOS_RECIPIENTS;
/
commit;
/

ALTER TABLE BJKT_BANSOS_RECIPIENTS_STG 
    DROP CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_C1;
/
ALTER TABLE BJKT_BANSOS_RECIPIENTS_STG 
    ADD CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_C1 
    CHECK (STATUS IN ('PENDING','VALID','ERROR','LOADED','SKIPPED'));
/
ALTER TABLE BJKT_UPLOAD_BANSOS ADD (
    SKIPPED_ROWS  NUMBER DEFAULT 0
);
/
ALTER TABLE BJKT_HISTORY_BANSOS_RECIPIENTS DROP (
    USER_APPROVE_ID
);
/
ALTER TABLE BJKT_HISTORY_BANSOS_RECIPIENTS ADD (
    USER_APPROVER VARCHAR2(200)
);
/

SELECT
    ROW_NUMBER() OVER (ORDER BY t.ID) AS NO,
    t.ID,
    t.NAMA,
    t.JEN_KELAMIN,
    t.TEMPAT_LAHIR,
    t.TANGGAL_LAHIR,
    t.NO_IDENTITAS,
    t.NAMA_IBU_KANDUNG_WALI,
    t.STATUS_KAWIN,
    t.AGAMA,
    t.PENDIDIKAN,
    t.ALAMAT_KTP,
    t.ALAMAT_DOMISILI,
    t.RT,
    t.RW,
    t.KELURAHAN,
    t.KECAMATAN,
    t.KOTA,
    t.PROPINSI,
    t.KODE_POS,
    t.STATUS_RUMAH,
    t.TELP_HP,
    t.PEKERJAAN_BIDANG_USAHA,
    t.KODE_PROFESI,
    t.STATUS_PEKERJAAN,
    t.NAMA_INSTANSI,
    t.ALAMAT_INSTANSI,
    t.KODE_POS_INSTANSI,
    t.NO_TELP_INSTANSI,
    t.SUAMI_ISTRI,
    t.NAMA_PIHAK_DIHUBUNGI,
    t.HUBUNGAN,
    t.ALAMAT,
    t.KOTA_DOMISILI,
    t.PROPINSI_DOMISILI,
    t.TELPON,
    t.STATUS_INSTANSI,
    t.NOMOR_INSTANSI,
    t.TOTAL_DANA,
    LISTAGG(
        REPLACE(jt.err_value, '\"', '"'), '<br>'
    ) WITHIN GROUP (ORDER BY jt.err_value) AS KETERANGAN_VALIDASI
FROM BJKT_BANSOS_RECIPIENTS_ERR t
CROSS JOIN JSON_TABLE(
    t.ERROR_DETAILS_JSON,
    '$[*]'
    COLUMNS (err_value VARCHAR2(1000) PATH '$.*')
) jt
WHERE t.PROGRAM_ID = 41
GROUP BY
    t.ID, t.NAMA, t.JEN_KELAMIN, t.TEMPAT_LAHIR, t.TANGGAL_LAHIR,
    t.NO_IDENTITAS, t.NAMA_IBU_KANDUNG_WALI, t.STATUS_KAWIN, t.AGAMA,
    t.PENDIDIKAN, t.ALAMAT_KTP, t.ALAMAT_DOMISILI, t.RT, t.RW,
    t.KELURAHAN, t.KECAMATAN, t.KOTA, t.PROPINSI, t.KODE_POS,
    t.STATUS_RUMAH, t.TELP_HP, t.PEKERJAAN_BIDANG_USAHA, t.KODE_PROFESI,
    t.STATUS_PEKERJAAN, t.NAMA_INSTANSI, t.ALAMAT_INSTANSI, t.KODE_POS_INSTANSI,
    t.NO_TELP_INSTANSI, t.SUAMI_ISTRI, t.NAMA_PIHAK_DIHUBUNGI, t.HUBUNGAN,
    t.ALAMAT, t.KOTA_DOMISILI, t.PROPINSI_DOMISILI, t.TELPON,
    t.STATUS_INSTANSI, t.NOMOR_INSTANSI, t.TOTAL_DANA;
/