/*
    -- START --
    CREATE TABLE TO STORE DATA MASTER PROGRAM
*/
DROP TABLE BJKT_MASTER_PROGRAMS;
/

CREATE TABLE BJKT_MASTER_PROGRAMS (
    ID                  NUMBER NOT NULL,
    CODE                VARCHAR2(255),
    NAME                VARCHAR2(255),
    YEAR                NUMBER,
    STAGE               NUMBER,
    BUDGET              NUMBER,
    GOVDEC              VARCHAR2(255),
    STATUS_DATA         NUMBER DEFAULT '1',
    ID_USER_REQUEST     NUMBER DEFAULT '2',
    BANK_ACCOUNT_NUM    VARCHAR2(200),        
    BANK_ACCOUNT_NAME   VARCHAR2(200),
    CREATED_BY          VARCHAR2(100),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(100),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_MASTER_PROGRAMS_PK PRIMARY KEY (ID)
);
/

DELETE FROM BJKT_MASTER_PROGRAMS;
/

COMMIT;
/

DROP INDEX BJKT_MASTER_PROGRAM_I1;
/

CREATE INDEX BJKT_MASTER_PROGRAMS_I1 ON BJKT_MASTER_PROGRAMS (BANK_ACCOUNT_NUM);
/

DROP INDEX BJKT_MASTER_PROGRAM_I2;
/

CREATE INDEX BJKT_MASTER_PROGRAMS_I2 ON BJKT_MASTER_PROGRAMS (STATUS_DATA);
/

DROP INDEX BJKT_MASTER_PROGRAM_I3
/

CREATE INDEX BJKT_MASTER_PROGRAMS_I3 ON BJKT_MASTER_PROGRAMS (GOVDEC);
/

DROP INDEX BJKT_MASTER_PROGRAM_I4;
/

CREATE INDEX BJKT_MASTER_PROGRAMS_I4 ON BJKT_MASTER_PROGRAMS (YEAR);
/

DROP SEQUENCE BJKT_MASTER_PROGRAM_S;
/

CREATE SEQUENCE BJKT_MASTER_PROGRAMS_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_MASTER_PROGRAMS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_MASTER_PROGRAMS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_MASTER_PROGRAMS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

/*
    -- END --
    CREATE TABLE TO STORE DATA MASTER PROGRAM
*/