-- LOV Jenis Kelamin
-- BJKT_BANSOS_JENIS_KELAMIN_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_JENIS_KELAMIN
WHERE STATUS_DATA = 1;
/

-- LOV Kebangsaan
-- BJKT_BANSOS_KEBANGSAAN_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_KEBANGSAAN
WHERE STATUS_DATA = 1;
/

-- LOV Status Kawin
-- BJKT_BANSOS_STATUS_KAWIN_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_STATUS_KAWIN
WHERE STATUS_DATA = 1;
/

-- LOV Agama
-- BJKT_BANSOS_AGAMA_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_AGAMA
WHERE STATUS_DATA = 1;
/

-- LOV Pendidikan
-- BJKT_BANSOS_PENDIDIKAN_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_PENDIDIKAN
WHERE STATUS_DATA = 1;
/

-- LOV Status Rumah
-- BJKT_BANSOS_STATUS_RUMAH_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_STATUS_RUMAH
WHERE STATUS_DATA = 1;
/

-- LOV Pekerjaan
-- BJKT_BANSOS_PEKERJAAN_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_PEKERJAAN
WHERE STATUS_DATA = 1;
/

-- LOV Profesi
-- BJKT_BANSOS_PROFESI_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_PROFESI
WHERE STATUS_DATA = 1;
/

-- LOV Status Pekerjaan
-- BJKT_BANSOS_STATUS_PEKERJAAN_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_STATUS_PEKERJAAN
WHERE STATUS_DATA = 1;
/

-- LOV Hubungan Keluarga
-- BJKT_BANSOS_HUB_KELUARGA_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_HUB_KELUARGA
WHERE STATUS_DATA = 1;
/

-- LOV Jenis Instansi
-- BJKT_BANSOS_JENIS_INSTANSI_LOV
SELECT KODE || ' - ' || DESKRIPSI d, KODE r
FROM BJKT_BANSOS_MASTER_JENIS_INSTANSI
WHERE STATUS_DATA = 1;
/