/*
    SAMPLE INSERT QUERY

    INSERT INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_AVG_BAL_CREDIT_MV', 'Y', 'C', 1, 'List data Avg. Balance Kredit Retail');
*/

-- Tabel konfigurasi: daftar MV yang akan di-refresh oleh scheduler
DROP TABLE BJKT_PNL_REFRESH_CONFIG;
/
CREATE TABLE BJKT_PNL_REFRESH_CONFIG (
    MV_NAME         VARCHAR2(100)   NOT NULL,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' NOT NULL,  -- Y/N
    REFRESH_METHOD  CHAR(1)         DEFAULT 'C' NOT NULL,  -- C/F/?
    REFRESH_ORDER   NUMBER          DEFAULT 99,            -- urutan eksekusi
    DESCRIPTION     VARCHAR2(255),
    CONSTRAINT BJKT_PNL_REFRESH_CONFIG_PK PRIMARY KEY (MV_NAME),
    CONSTRAINT BJKT_PNL_REFRESH_CONFIG_CK1 CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT BJKT_PNL_REFRESH_CONFIG_CK2 CHECK (REFRESH_METHOD IN ('C','F','?'))
);
/
CREATE INDEX BJKT_PNL_REFRESH_CONFIG_I1 ON BJKT_PNL_REFRESH_CONFIG (IS_ACTIVE);
/
CREATE INDEX BJKT_PNL_REFRESH_CONFIG_I2 ON BJKT_PNL_REFRESH_CONFIG (REFRESH_ORDER);
/

-- Tabel log: rekaman hasil setiap eksekusi refresh
DROP TABLE BJKT_PNL_REFRESH_LOG;
/
CREATE TABLE BJKT_PNL_REFRESH_LOG (
    LOG_ID          VARCHAR2(300)   DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'DDMMYYYYHH24MISSFF3') NOT NULL,
    MV_NAME         VARCHAR2(100),
    REFRESH_START   TIMESTAMP       DEFAULT SYSTIMESTAMP,
    REFRESH_END     TIMESTAMP,
    DURATION_SEC    NUMBER,
    STATUS          VARCHAR2(10), -- SUCCESS / FAILED
    ERROR_MESSAGE   VARCHAR2(4000),
    CONSTRAINT BJKT_PNL_REFRESH_LOG_PK PRIMARY KEY (LOG_ID)
);
/
CREATE INDEX BJKT_PNL_REFRESH_LOG_I1 ON BJKT_PNL_REFRESH_LOG (MV_NAME);
/
CREATE INDEX BJKT_PNL_REFRESH_LOG_I2 ON BJKT_PNL_REFRESH_LOG (REFRESH_START);
/

