INSERT ALL

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_AVG_BAL_CREDIT_MV', 'Y', 'C', 1, 'List data Avg. Balance Kredit Retail')
    
    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_AVG_BAL_DPK_MV', 'Y', 'C', 1, 'List data Avg. Balance DPK')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_PEN_BUNGA_TOTAL_MV', 'Y', 'C', 1, 'List data Pendapatan Bunga')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_BEBAN_BUNGA_TOTAL_MV', 'Y', 'C', 1, 'List data beban bunga total')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_FTP_INCOME_MV', 'Y', 'C', 1, 'List data FTP Income')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_FTP_CHARGE_MV', 'Y', 'C', 1, 'List data FTP Charge Loan')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_FEE_BASED_INCOME_MV', 'Y', 'C', 1, 'List data Fee Based Income')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_NII_POST_FTP_MV', 'Y', 'C', 1, 'List data NII-Post FTP')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_DIRECT_OPEX_MV', 'Y', 'C', 1, 'List data Direct OPEX')

    INTO BJKT_PNL_REFRESH_CONFIG (MV_NAME, IS_ACTIVE, REFRESH_METHOD, REFRESH_ORDER, DESCRIPTION)
    VALUES ('BJKT_PNL_BEBAN_CKPN_MV', 'Y', 'C', 1, 'List data Beban CKPN')

SELECT * FROM dual;
/
COMMIT;
/