/*
    -- START --
    CREATE TABLE TO STORE AND MANAGE REFERAL CODE
*/
-- DROP TABLE BJKT_DIGSLIP_KODE_REFERAL;
-- /
CREATE TABLE BJKT_DIGSLIP_KODE_REFERAL (
    ID                      NUMBER          NOT NULL,
    KODE_REF                VARCHAR2(6)     NOT NULL,
    ID_TRANSAKSI            NUMBER          NOT NULL,
    TIPE_TRANSAKSI          VARCHAR2(25)    NOT NULL,
    STATUS                  VARCHAR2(20)    NOT NULL,
    EXPIRED_AT              TIMESTAMP       NOT NULL,
    GENERATE_DATE           TIMESTAMP       NOT NULL,
    PROCESS_CABANG_CODE     VARCHAR2(3),             
    PROCESSED_AT            TIMESTAMP,
    PROCESSED_BY            VARCHAR2(50),
    COMPLETED_AT            TIMESTAMP,
    COMPLETED_BY            VARCHAR2(50),
    CANCELLED_AT            TIMESTAMP,
    CANCELLED_BY            VARCHAR2(50),
    CANCEL_REASON           VARCHAR2(255),
    EXPIRED_PROCESSED_AT    TIMESTAMP,
    EXPIRED_PROCESSED_BY    VARCHAR2(50),
    CREATED_DATE            TIMESTAMP       NOT NULL,
    LAST_UPDATED_BY         VARCHAR2(50),
    LAST_UPDATE_DATE        TIMESTAMP,

    PARENT_ID               NUMBER,
    STEP_NO                 NUMBER          DEFAULT 1 NOT NULL,
    ROOT_PARENT_ID          NUMBER,

    CONSTRAINT BJKT_DIGSLIP_KODE_REFERAL_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_DIGSLIP_KODE_REFERAL_FK1 FOREIGN KEY (PARENT_ID) REFERENCES BJKT_DIGSLIP_KODE_REFERAL (ID),
    CONSTRAINT BJKT_DIGSLIP_KODE_REFERAL_CK1 CHECK (TIPE_TRANSAKSI IN (
        'SETOR_TUNAI','TARIK_TUNAI','PINDAH_BUKU', 'TRANSFER_SKN', 'TRANSFER_RTGS', 'PENGKINIAN_DATA', 'PELAKU_TRANSAKSI'
    )),
    CONSTRAINT BJKT_DIGSLIP_KODE_REFERAL_CK2 CHECK (STATUS IN (
        'GENERATED','PROCESSED','COMPLETED','CANCELLED','EXPIRED'
    ))
);
CREATE INDEX BJKT_DIGSLIP_KODE_REFERALA_I1 ON BJKT_DIGSLIP_KODE_REFERAL (KODE_REF, TIPE_TRANSAKSI, ID_TRANSAKSI)
/
CREATE UNIQUE INDEX BJKT_DIGSLIP_KODE_REFERAL_U1
    ON BJKT_DIGSLIP_KODE_REFERAL (
        CASE
            WHEN PARENT_ID IS NULL
                 AND STATUS NOT IN ('COMPLETED','CANCELLED','EXPIRED')
            THEN KODE_REF
        END
    );
/
-- DROP SEQUENCE BJKT_DIGSLIP_KODE_REFERAL_S;
-- /
CREATE SEQUENCE BJKT_DIGSLIP_KODE_REFERAL_S START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER BJKT_DIGSLIP_KODE_REFERAL_TRG
BEFORE INSERT OR UPDATE
ON BJKT_DIGSLIP_KODE_REFERAL
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_DIGSLIP_KODE_REFERAL_S.NEXTVAL);
        :NEW.CREATED_DATE := SYSTIMESTAMP;
        :NEW.GENERATE_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE AND MANAGE REFERAL CODE
*/