/*
    -- START --
    CREATE TABLE TO STORE CREDENTIAL
*/
DROP TABLE BDKI_FND_CREDENTIAL;
/

CREATE TABLE DEV.BDKI_FND_CREDENTIAL (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(200),
    URL VARCHAR2(200),
    VERSION VARCHAR2(10),
    CREDENTIAL_STATIC_ID VARCHAR2(255),
    CHANNEL_ID VARCHAR2(100),
    USER_NAME VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    WALLET_PATH VARCHAR2(100),
    WALLET_PASSWORD VARCHAR2(100),
    PUBLIC_KEY VARCHAR2(4000),
    PRIVATE_KEY VARCHAR2(4000),
    CLIENT_ID VARCHAR2(4000),
    CLIENT_KEY VARCHAR2(4000),
    SECRET_KEY VARCHAR2(4000),
    API_KEY VARCHAR2(4000),
    API_SECRET VARCHAR2(4000),
    ATTRIBUTE_CATEGORY VARCHAR2(150),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    ATTRIBUTE6 VARCHAR2(150),
    ATTRIBUTE7 VARCHAR2(150),
    ATTRIBUTE8 VARCHAR2(150),
    ATTRIBUTE9 VARCHAR2(150),
    ATTRIBUTE10 VARCHAR2(150),
    ATTRIBUTE11 VARCHAR2(150),
    ATTRIBUTE12 VARCHAR2(150),
    ATTRIBUTE13 VARCHAR2(150),
    ATTRIBUTE14 VARCHAR2(150),
    ATTRIBUTE15 VARCHAR2(150),

    IFACE_MODE VARCHAR2(30),
    IFACE_STATUS VARCHAR2(100),
    IFACE_MESSAGE VARCHAR2(4000),

    CREATED_BY VARCHAR2(100),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_LOGIN NUMBER,
    LAST_UPDATED_BY VARCHAR2(100),
    LAST_UPDATE_DATE TIMESTAMP
);
/

CREATE SEQUENCE DEV.BDKI_FND_CREDENTIAL_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER DEV.BDKI_FND_CREDENTIAL_TRG
BEFORE INSERT OR UPDATE
ON DEV.BDKI_FND_CREDENTIAL
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, DEV.BDKI_FND_CREDENTIAL_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE CREDENTIAL
*/

/*
    -- START --
    CREATE TABLE TO STORE LOG API
*/
CREATE TABLE DEV.BDKI_API_LOG (
    LOG_ID VARCHAR2(300) 
        DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'DDMMYYYYHH24MISSFF3')
        PRIMARY KEY,

    BANK_NAME VARCHAR2(300),
    URL VARCHAR2(1000),
    ACCESS_TOKEN VARCHAR2(1000),
    CONTENT_TYPE VARCHAR2(1000),
    AUTHORIZATION VARCHAR2(1000),
    PARTNER_ID VARCHAR2(1000),
    TIME_STAMP VARCHAR2(1000),
    SIGNATURE VARCHAR2(1000),
    EXTERNAL_ID VARCHAR2(1000),
    CHANNEL_ID VARCHAR2(1000),

    HEADER CLOB,
    REQUEST CLOB,
    RESPONSE CLOB,

    ATTRIBUTE_CATEGORY VARCHAR2(150),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    ATTRIBUTE6 VARCHAR2(150),
    ATTRIBUTE7 VARCHAR2(150),
    ATTRIBUTE8 VARCHAR2(150),
    ATTRIBUTE9 VARCHAR2(150),
    ATTRIBUTE10 VARCHAR2(150),
    ATTRIBUTE11 VARCHAR2(150),
    ATTRIBUTE12 VARCHAR2(150),
    ATTRIBUTE13 VARCHAR2(150),
    ATTRIBUTE14 VARCHAR2(150),
    ATTRIBUTE15 VARCHAR2(150),

    IFACE_MODE VARCHAR2(30),
    IFACE_STATUS VARCHAR2(100),
    IFACE_MESSAGE VARCHAR2(4000),

    CREATED_BY VARCHAR2(100),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_LOGIN NUMBER,
    LAST_UPDATED_BY VARCHAR2(100),
    LAST_UPDATE_DATE TIMESTAMP
);
/

CREATE OR REPLACE TRIGGER DEV.BDKI_API_LOG_TRG
BEFORE INSERT OR UPDATE
ON DEV.BDKI_API_LOG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSDATE;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSDATE;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE LOG API
*/