/*
    -- START --
    CREATE TABLE TO STORE CREDENTIAL
*/
DROP TABLE BDKI_FND_CREDENTIAL;
/

CREATE TABLE DEV.BJKT_FND_CREDENTIAL (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(200),
    URL VARCHAR2(200),
    VERSION VARCHAR2(10),
    CREDENTIAL_STATIC_ID VARCHAR2(255),
    CHANNEL_ID VARCHAR2(100),
    USER_NAME VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    WALLET_PATH VARCHAR2(100),
    WALLET_PASSWORD VARCHAR2(100),
    PUBLIC_KEY VARCHAR2(4000),
    PRIVATE_KEY VARCHAR2(4000),
    CLIENT_ID VARCHAR2(4000),
    CLIENT_KEY VARCHAR2(4000),
    SECRET_KEY VARCHAR2(4000),
    API_KEY VARCHAR2(4000),
    API_SECRET VARCHAR2(4000),
    ATTRIBUTE_CATEGORY VARCHAR2(150),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    ATTRIBUTE6 VARCHAR2(150),
    ATTRIBUTE7 VARCHAR2(150),
    ATTRIBUTE8 VARCHAR2(150),
    ATTRIBUTE9 VARCHAR2(150),
    ATTRIBUTE10 VARCHAR2(150),
    ATTRIBUTE11 VARCHAR2(150),
    ATTRIBUTE12 VARCHAR2(150),
    ATTRIBUTE13 VARCHAR2(150),
    ATTRIBUTE14 VARCHAR2(150),
    ATTRIBUTE15 VARCHAR2(150),

    IFACE_MODE VARCHAR2(30),
    IFACE_STATUS VARCHAR2(100),
    IFACE_MESSAGE VARCHAR2(4000),

    CREATED_BY VARCHAR2(100),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_LOGIN NUMBER,
    LAST_UPDATED_BY VARCHAR2(100),
    LAST_UPDATE_DATE TIMESTAMP
);
/

DROP SEQUENCE DEV.BDKI_FND_CREDENTIAL_S;
/

CREATE SEQUENCE DEV.BJKT_FND_CREDENTIAL_S
START WITH 1
INCREMENT BY 1;
/

DROP TRIGGER DEV.BDKI_FND_CREDENTIAL_TRG;
/

CREATE OR REPLACE TRIGGER DEV.BJKT_FND_CREDENTIAL_TRG
BEFORE INSERT OR UPDATE
ON DEV.BJKT_FND_CREDENTIAL
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, DEV.BJKT_FND_CREDENTIAL_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE CREDENTIAL
*/

/*
    -- START --
    CREATE TABLE TO STORE LOG API
*/
DROP TABLE DEV.BJKT_API_LOG;
/

CREATE TABLE DEV.BJKT_API_LOG (
    LOG_ID VARCHAR2(300) 
        DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'DDMMYYYYHH24MISSFF3')
        PRIMARY KEY,

    NAME VARCHAR2(300),
    URL VARCHAR2(1000),
    ACCESS_TOKEN VARCHAR2(1000),
    CONTENT_TYPE VARCHAR2(1000),
    AUTHORIZATION VARCHAR2(1000),
    PARTNER_ID VARCHAR2(1000),
    TIME_STAMP VARCHAR2(1000),
    SIGNATURE VARCHAR2(1000),
    EXTERNAL_ID VARCHAR2(1000),
    CHANNEL_ID VARCHAR2(1000),
    RAY_ID VARCHAR2(20),

    HEADER CLOB,
    REQUEST CLOB,
    RESPONSE CLOB,

    ATTRIBUTE_CATEGORY VARCHAR2(150),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    ATTRIBUTE6 VARCHAR2(150),
    ATTRIBUTE7 VARCHAR2(150),
    ATTRIBUTE8 VARCHAR2(150),
    ATTRIBUTE9 VARCHAR2(150),
    ATTRIBUTE10 VARCHAR2(150),
    ATTRIBUTE11 VARCHAR2(150),
    ATTRIBUTE12 VARCHAR2(150),
    ATTRIBUTE13 VARCHAR2(150),
    ATTRIBUTE14 VARCHAR2(150),
    ATTRIBUTE15 VARCHAR2(150),

    IFACE_MODE VARCHAR2(30),
    IFACE_STATUS VARCHAR2(100),
    IFACE_MESSAGE VARCHAR2(4000),

    CREATED_BY VARCHAR2(100),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_LOGIN NUMBER,
    LAST_UPDATED_BY VARCHAR2(100),
    LAST_UPDATE_DATE TIMESTAMP
);
/

DROP TRIGGER DEV.BDKI_API_LOG_TRG;
/

CREATE OR REPLACE TRIGGER DEV.BJKT_API_LOG_TRG
BEFORE INSERT OR UPDATE
ON DEV.BJKT_API_LOG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSDATE;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSDATE;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE LOG API
*/

/*
    -- START --
    CREATE TABLE TO STORE TOKEN
*/

CREATE TABLE DEV.BJKT_ACCESS_TOKEN (
    ID            NUMBER PRIMARY KEY,
    ACCESS_TOKEN        VARCHAR2(4000),
    TIMESTAMP_TOKEN     VARCHAR2(200),
    EXPIRED_AT          NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP
);
/

CREATE SEQUENCE DEV.BJKT_ACCESS_TOKEN_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER DEV.BJKT_ACCESS_TOKEN_TRG
BEFORE INSERT OR UPDATE
ON DEV.BJKT_ACCESS_TOKEN
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, DEV.BJKT_ACCESS_TOKEN_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;

/*
    -- END --
    CREATE TABLE TO STORE TOKEN
*/