create or replace package "BJKT_SSO_INTEGRATIONS_PKG" as
    
    FUNCTION GET_EXIST_TOKEN RETURN VARCHAR2;

    FUNCTION GET_ACCESS_TOKEN (
        P_TIMESTAMP IN VARCHAR2
    ) RETURN VARCHAR2;

    PROCEDURE GET_DIVISIONS (
        R_STATUS    OUT VARCHAR2,
        R_MESSAGE   OUT VARCHAR2
    );

end "BJKT_SSO_INTEGRATIONS_PKG";
/