/*
   START
   CREATE TABLE TO STORE FILE UPLOAD PROGRAM BANSOS
*/

DELETE FROM BJKT_FILE_UPLOAD_LOG;
/
COMMIT;
/

DROP TABLE BJKT_UPLOAD_BANSOS;
/

CREATE SEQUENCE BJKT_UPLOAD_BANSOS_BATCH_S START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE TABLE BJKT_UPLOAD_BANSOS (
    ID                  NUMBER NOT NULL,
    BATCH_ID            NUMBER NOT NULL,
    PROGRAM_ID          NUMBER NOT NULL,
    FILE_LOG_ID         NUMBER NOT NULL,
    TOTAL_ROWS          NUMBER,
    VALID_ROWS          NUMBER,
    ERROR_ROWS          NUMBER,
    LOADED_ROWS         NUMBER,
    STATUS              VARCHAR2(50) DEFAULT 'PROCESSING',
    MESSAGE             VARCHAR2(4000),
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    FINISHED_AT         TIMESTAMP,

    CONSTRAINT BJKT_UPLOAD_BANSOS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_UPLOAD_BANSOS_U1 UNIQUE (FILE_LOG_ID),
    CONSTRAINT BJKT_UPLOAD_BANSOS_C1 CHECK (STATUS IN ('PROCESSING','PARTIAL','SUCCESS','ERROR'))
);
/

CREATE INDEX BJKT_UPLOAD_BANSOS_I1 ON BJKT_UPLOAD_BANSOS(PROGRAM_ID, STATUS);
/
CREATE INDEX BJKT_UPLOAD_BANSOS_I2 ON BJKT_UPLOAD_BANSOS(STATUS);
/

CREATE SEQUENCE BJKT_UPLOAD_BANSOS_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_UPLOAD_BANSOS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_UPLOAD_BANSOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_UPLOAD_BANSOS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

/*
   END
   CREATE TABLE TO STORE FILE UPLOAD PROGRAM BANSOS
*/
DROP TABLE BJKT_BANSOS_RECIPIENTS_STG;
/

CREATE TABLE BJKT_BANSOS_RECIPIENTS_STG (
    ID                      NUMBER NOT NULL,
    BATCH_ID                NUMBER NOT NULL,
    UPLOAD_BANSOS_ID        NUMBER NOT NULL, 
    LINE_NUMBER             NUMBER,

    -- kolom raw (VARCHAR2 semua, belum dikonversi)
    NAMA                    VARCHAR2(500),
    JEN_KELAMIN             VARCHAR2(100),
    KEBANGSAAN              VARCHAR2(100),
    TEMPAT_LAHIR            VARCHAR2(200),
    TANGGAL_LAHIR           VARCHAR2(50),
    NO_IDENTITAS            VARCHAR2(50),
    NAMA_IBU_KANDUNG_WALI   VARCHAR2(500),
    STATUS_KAWIN            VARCHAR2(100),
    AGAMA                   VARCHAR2(100),
    PENDIDIKAN              VARCHAR2(100),
    ALAMAT_KTP              VARCHAR2(1000),
    ALAMAT_DOMISILI         VARCHAR2(1000),
    RT                      VARCHAR2(10),
    RW                      VARCHAR2(10),
    KELURAHAN               VARCHAR2(200),
    KECAMATAN               VARCHAR2(200),
    KOTA                    VARCHAR2(200),
    PROPINSI                VARCHAR2(200),
    KODE_POS                VARCHAR2(20),
    STATUS_RUMAH            VARCHAR2(100),
    TELP_HP                 VARCHAR2(50),
    PEKERJAAN_BIDANG_USAHA  VARCHAR2(200),
    KODE_PROFESI            VARCHAR2(100),
    STATUS_PEKERJAAN        VARCHAR2(100),
    NAMA_INSTANSI           VARCHAR2(500),
    ALAMAT_INSTANSI         VARCHAR2(1000),
    KODE_POS_INSTANSI       VARCHAR2(20),
    NO_TELP_INSTANSI        VARCHAR2(50),
    SUAMI_ISTRI             VARCHAR2(200),
    NAMA_PIHAK_DIHUBUNGI    VARCHAR2(500),
    HUBUNGAN                VARCHAR2(100),
    ALAMAT                  VARCHAR2(1000),
    KOTA_DOMISILI           VARCHAR2(200),
    PROPINSI_DOMISILI       VARCHAR2(200),
    TELPON                  VARCHAR2(50),
    NOMOR_INSTANSI          VARCHAR2(100),
    STATUS_INSTANSI         VARCHAR2(100),
    TOTAL_DANA              VARCHAR2(50),

    /* 
        Status Baris
        - PENDING  : baru masuk dari CSV
        - VALID    : lolos semua validasi master
        - ERROR    : gagal validasi master atau DB constraint
        - LOADED   : berhasil masuk BJKT_HISTORY_BANSOS_RECIPIENTS
    */
    STATUS                   VARCHAR2(20) DEFAULT 'PENDING',

    -- Flag Error per Kolom (Y = error, NULL = ok)
    ERR_NAMA                 VARCHAR2(1),
    ERR_JEN_KELAMIN          VARCHAR2(1),
    ERR_KEBANGSAAN           VARCHAR2(1),
    ERR_AGAMA                VARCHAR2(1),
    ERR_PENDIDIKAN           VARCHAR2(1),
    ERR_STATUS_KAWIN         VARCHAR2(1),
    ERR_STATUS_RUMAH         VARCHAR2(1),
    ERR_PEKERJAAN            VARCHAR2(1),
    ERR_KODE_PROFESI         VARCHAR2(1),
    ERR_STATUS_PEKERJAAN     VARCHAR2(1),
    ERR_HUBUNGAN             VARCHAR2(1),
    ERR_STATUS_INSTANSI      VARCHAR2(1),
    ERR_TANGGAL_LAHIR        VARCHAR2(1),
    ERR_NO_IDENTITAS         VARCHAR2(1),
    ERR_FINAL_INSERT         VARCHAR2(1),

    MSG_NAMA                 VARCHAR2(500),
    MSG_JEN_KELAMIN          VARCHAR2(500),
    MSG_KEBANGSAAN           VARCHAR2(500),
    MSG_AGAMA                VARCHAR2(500),
    MSG_PENDIDIKAN           VARCHAR2(500),
    MSG_STATUS_KAWIN         VARCHAR2(500),
    MSG_STATUS_RUMAH         VARCHAR2(500),
    MSG_PEKERJAAN            VARCHAR2(500),
    MSG_KODE_PROFESI         VARCHAR2(500),
    MSG_STATUS_PEKERJAAN     VARCHAR2(500),
    MSG_HUBUNGAN             VARCHAR2(500),
    MSG_STATUS_INSTANSI      VARCHAR2(500),
    MSG_TANGGAL_LAHIR        VARCHAR2(500),
    MSG_NO_IDENTITAS         VARCHAR2(500),
    MSG_FINAL_INSERT         VARCHAR2(1000),

    ERROR_COLUMNS            VARCHAR2(4000), -- daftar kolom yang gagal, dipisah koma
    CREATED_AT               TIMESTAMP,
    CREATED_BY               VARCHAR2(200),
    VALIDATED_AT             TIMESTAMP,
    LOADED_AT                TIMESTAMP,

    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_FK FOREIGN KEY (UPLOAD_BANSOS_ID) REFERENCES BJKT_UPLOAD_BANSOS (ID),
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_C1 CHECK (STATUS IN ('PENDING','VALID','ERROR','LOADED'))
);
/

CREATE INDEX BJKT_BANSOS_RECIPIENTS_STG_I1 ON BJKT_BANSOS_RECIPIENTS_STG (BATCH_ID, STATUS);
/
CREATE INDEX BJKT_BANSOS_RECIPIENTS_STG_I2 ON BJKT_BANSOS_RECIPIENTS_STG (BATCH_ID, LINE_NUMBER);
/

CREATE SEQUENCE BJKT_BANSOS_RECIPIENTS_STG_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_BANSOS_RECIPIENTS_STG_TRG
BEFORE INSERT
ON BJKT_BANSOS_RECIPIENsTS_STG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_HISTORY_BANSOS_RECIPIENTS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

