/*
   START
   CREATE TABLE TO STORE FILE UPLOAD PROGRAM BANSOS
*/

CREATE TABLE BJKT_UPLOAD_BANSOS (
    ID                  NUMBER NOT NULL,
    PROGRAM_ID          NUMBER NOT NULL,
    FILE_LOG_ID         NUMBER NOT NULL,
    TOTAL_DATA          NUMBER,
    TOTAL_VALID_DATA    NUMBER,
    TOTAL_INVALID_DATA  NUMBER,
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(200),
    LAST_UPDATE_DATE    TIMESTAMP,

    CONSTRAINT BJKT_UPLOAD_BANSOS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_UPLOAD_BANSOS_U1 UNIQUE (FILE_LOG_ID)
);
/

CREATE INDEX BJKT_UPLOAD_BANSOS_I1 ON BJKT_UPLOAD_BANSOS(PROGRAM_ID);
/

CREATE SEQUENCE BJKT_UPLOAD_BANSOS_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_UPLOAD_BANSOS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_UPLOAD_BANSOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_UPLOAD_BANSOS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

/*
   END
   CREATE TABLE TO STORE FILE UPLOAD PROGRAM BANSOS
*/

/*
    -- START --
    CREATE TABLE TO STORE DATA PENERIMA BANSOS
*/
DROP TABLE BJKT_HISTORY_BANSOS_RECIPIENTS;
/

CREATE TABLE BJKT_HISTORY_BANSOS_RECIPIENTS (
    ID                          NUMBER NOT NULL,
    NAME                        VARCHAR2(255),
    GENDER_MASTER_CODE          VARCHAR2(255),
    NATIONALITY_MASTER_CODE     VARCHAR2(255),
    BORN_PLACE                  VARCHAR2(255),
    BORN_DATE                   DATE,
    IDENTITY_CARD_NUM           VARCHAR2(255),
    MOTHER_OR_GUARDIAN_NAME     VARCHAR2(255),
    RELIGION_MASTER_CODE        VARCHAR2(255),
    EDUCATION_MASTER_CODE       VARCHAR2(255),

    ID_CARD_ADDRESS         VARCHAR2(1000),
    DOMICILE_ADDRESS        VARCHAR2(1000),
    RT                      VARCHAR2(50),
    RW                      VARCHAR2(50),
    VILLAGE                 VARCHAR2(255),
    DISTRICT                VARCHAR2(255),
    CITY                    VARCHAR2(255),
    PROVINCE                VARCHAR2(255),
    POSTAL_CODE             VARCHAR2(50),
    PHONE_NUM               VARCHAR2(50),

    INSTITUTION_NUM                 VARCHAR2(200),
    INSTITUTION_NAME                VARCHAR2(255),
    INSTITUTION_ADDRESS             VARCHAR2(1000),
    INSTITUTION_POSTAL_CODE         VARCHAR2(50),
    INSTITUTION_PHONE_NUM           VARCHAR2(50),
    INTITUTION_TYPE_MASTER_CODE     VARCHAR2(200),

    CONTACT_PERSON_NAME             VARCHAR2(255),
    FAMILY_RELATIONSHIP_MASTER_CODE VARCHAR2(255),
    CONTACT_PERSON_ADDRESS          VARCHAR2(255),
    CONTACT_PERSON_CITY             VARCHAR2(255),
    CONTACT_PERSON_PROVINCE         VARCHAR2(255),
    CONTACT_PERSON_PHONE_NUM        VARCHAR2(50),

    MARRIAGE_STATUS_CODE            VARCHAR2(255),
    HOUSE_MASTER_STATUS_CODE        VARCHAR2(255),
    JOB_MASTER_CODE                 VARCHAR2(255),
    PROFESSION_MASTER_CODE          VARCHAR2(255),
    JOB_STATUS_MASTER_CODE          VARCHAR2(255),

    HUSBAND_WIFE                    VARCHAR2(255),

    PROCESS_STATUS_MASTER_CODE      VARCHAR2(255) DEFAULT '0',
    DISTRIBUTION_STATUS_MASTER_CODE VARCHAR2(255) DEFAULT '00',
    FUND_MASTER_STATUS_CODE         VARCHAR2(255) DEFAULT '3',
    ACCOUNT_MASTER_STATUS_CODE      VARCHAR2(255) DEFAULT '3',

    PROGRAM_MASTER_CODE             VARCHAR2(255),

    USER_APPROVE_ID                 NUMBER,

    UPLOAD_CODE                     VARCHAR2(255),
    UPLOAD_DATE                     TIMESTAMP,

    /*
        VALIDATION FLAG:
        0 = Belum divalidasi
        1 = Valid
        2 = Tidak valid
    */
    VALIDATION_FLAG                 NUMBER(1) DEFAULT 0,
    VALIDATION_NOTES                CLOB,

    FUND_AMOUNT                     NUMBER,
    BANK_ACCOUNT_NUM                VARCHAR2(255),

    RECIPIENT_STATUS_MASTER_STATUS  VARCHAR2(255) DEFAULT '00',
    DEBIT_CARD_NUM                  VARCHAR2(255),

    DISTRIBUTION_MANAGER                VARCHAR2(255),
    DISTRIBUTION_PLACE                  VARCHAR2(1000),
    DEBIT_CREDIT_STATUS_MASTER_CODE     VARCHAR2(100),
    DISTRIBUTION_LOCATION_MASTER_CODE   VARCHAR2(200),

    PROCESS_DATE                    CLOB,

    ID_USER_REQUEST                 NUMBER DEFAULT 0,

    UPLOAD_DANA_IS_APPROVE          NUMBER(1) DEFAULT 0,
    TOTAL_DANA                      NUMBER,

    CREATED_BY                      VARCHAR2(200),
    CREATION_DATE                   TIMESTAMP,
    LAST_UPDATED_BY                 VARCHAR2(200),
    LAST_UPDATE_DATE                TIMESTAMP,

    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_C1 CHECK (VALIDATION_FLAG IN (0, 1, 2)),
    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_C2 CHECK (VALIDATION_NOTES IS JSON),
    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_C3 CHECK (PROCESS_DATE IS JSON)
);
/

CREATE INDEX BJKT_HISTORY_BANSOS_RECIPIENTS_I1 ON BJKT_HISTORY_BANSOS_RECIPIENTS (PROGRAM_MASTER_CODE);
/
CREATE INDEX BJKT_HISTORY_BANSOS_RECIPIENTS_I2 ON BJKT_HISTORY_BANSOS_RECIPIENTS (PROGRAM_MASTER_CODE, IDENTITY_CARD_NUM);
/

CREATE SEQUENCE BJKT_HISTORY_BANSOS_RECIPIENTS_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_HISTORY_BANSOS_RECIPIENTS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_HISTORY_BANSOS_RECIPIENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_HISTORY_BANSOS_RECIPIENTS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;

/*
    -- END --
    CREATE TABLE TO STORE DATA PENERIMA BANSOS
*/