/*
   START
   CREATE TABLE TO STORE FILE UPLOAD PROGRAM BANSOS
*/
DROP TABLE BJKT_UPLOAD_BANSOS;
/

CREATE SEQUENCE BJKT_UPLOAD_BANSOS_BATCH_S START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE TABLE BJKT_UPLOAD_BANSOS (
    ID                  NUMBER NOT NULL,
    BATCH_ID            NUMBER NOT NULL,
    PROGRAM_ID          NUMBER NOT NULL,
    FILE_LOG_ID         NUMBER,
    TOTAL_ROWS          NUMBER,
    VALID_ROWS          NUMBER,
    ERROR_ROWS          NUMBER,
    LOADED_ROWS         NUMBER,
    SKIPPED_ROWS        NUMBER DEFAULT 0,
    NEW_RECIPIENTS      NUMBER DEFAULT 0,
    OLD_RECIPIENTS      NUMBER DEFAULT 0,
    STATUS              VARCHAR2(50) DEFAULT 'PROCESSING',
    MESSAGE             VARCHAR2(4000),
    CREATED_BY          VARCHAR2(200),
    CREATION_DATE       TIMESTAMP,
    FINISHED_AT         TIMESTAMP,

    CONSTRAINT BJKT_UPLOAD_BANSOS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_UPLOAD_BANSOS_FK FOREIGN KEY (PROGRAM_ID) 
        REFERENCES BJKT_MASTER_PROGRAMS(ID) ON DELETE CASCADE,
    CONSTRAINT BJKT_UPLOAD_BANSOS_U1 UNIQUE (FILE_LOG_ID),
    CONSTRAINT BJKT_UPLOAD_BANSOS_U2 UNIQUE (BATCH_ID),
    CONSTRAINT BJKT_UPLOAD_BANSOS_C1 CHECK (STATUS IN ('PROCESSING','PARTIAL','SUCCESS','ERROR'))
);
/

CREATE INDEX BJKT_UPLOAD_BANSOS_I1 ON BJKT_UPLOAD_BANSOS(PROGRAM_ID, STATUS);
/
CREATE INDEX BJKT_UPLOAD_BANSOS_I2 ON BJKT_UPLOAD_BANSOS(STATUS);
/

CREATE SEQUENCE BJKT_UPLOAD_BANSOS_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_UPLOAD_BANSOS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_UPLOAD_BANSOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_UPLOAD_BANSOS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

/*
   END
   CREATE TABLE TO STORE FILE UPLOAD PROGRAM BANSOS
*/

/*
   START
   CREATE TABLE TO STORE DATA STAGGING PENERIMA BANSOS
*/
DROP TABLE BJKT_BANSOS_RECIPIENTS_STG;
/

CREATE TABLE BJKT_BANSOS_RECIPIENTS_STG (
    ID                      NUMBER NOT NULL,
    BATCH_ID                NUMBER NOT NULL,
    UPLOAD_BANSOS_ID        NUMBER NOT NULL,
    PROGRAM_ID              NUMBER NOT NULL,
    LINE_NUMBER             NUMBER,

    -- kolom raw (VARCHAR2 semua, belum dikonversi)
    NAMA                    VARCHAR2(500),
    JEN_KELAMIN             VARCHAR2(100),
    KEBANGSAAN              VARCHAR2(100),
    TEMPAT_LAHIR            VARCHAR2(200),
    TANGGAL_LAHIR           VARCHAR2(50),
    NO_IDENTITAS            VARCHAR2(50),
    NAMA_IBU_KANDUNG_WALI   VARCHAR2(500),
    STATUS_KAWIN            VARCHAR2(100),
    AGAMA                   VARCHAR2(100),
    PENDIDIKAN              VARCHAR2(100),
    ALAMAT_KTP              VARCHAR2(1000),
    ALAMAT_DOMISILI         VARCHAR2(1000),
    RT                      VARCHAR2(10),
    RW                      VARCHAR2(10),
    KELURAHAN               VARCHAR2(200),
    KECAMATAN               VARCHAR2(200),
    KOTA                    VARCHAR2(200),
    PROPINSI                VARCHAR2(200),
    KODE_POS                VARCHAR2(20),
    STATUS_RUMAH            VARCHAR2(100),
    TELP_HP                 VARCHAR2(50),
    PEKERJAAN_BIDANG_USAHA  VARCHAR2(200),
    KODE_PROFESI            VARCHAR2(100),
    STATUS_PEKERJAAN        VARCHAR2(100),
    NAMA_INSTANSI           VARCHAR2(500),
    ALAMAT_INSTANSI         VARCHAR2(1000),
    KODE_POS_INSTANSI       VARCHAR2(20),
    NO_TELP_INSTANSI        VARCHAR2(50),
    SUAMI_ISTRI             VARCHAR2(200),
    NAMA_PIHAK_DIHUBUNGI    VARCHAR2(500),
    HUBUNGAN                VARCHAR2(100),
    ALAMAT                  VARCHAR2(1000),
    KOTA_DOMISILI           VARCHAR2(200),
    PROPINSI_DOMISILI       VARCHAR2(200),
    TELPON                  VARCHAR2(50),
    NOMOR_INSTANSI          VARCHAR2(100),
    STATUS_INSTANSI         VARCHAR2(100),
    TOTAL_DANA              VARCHAR2(50),

    /* 
        Status Baris
        - PENDING  : baru masuk dari CSV
        - VALID    : lolos semua validasi master
        - ERROR    : gagal validasi master atau DB constraint
        - LOADED   : berhasil masuk BJKT_HISTORY_BANSOS_RECIPIENTS
    */
    STATUS                   VARCHAR2(20) DEFAULT 'PENDING',

    -- Flag Error per Kolom (Y = error, NULL = ok)
    ERR_NAMA                 VARCHAR2(1),
    ERR_JEN_KELAMIN          VARCHAR2(1),
    ERR_KEBANGSAAN           VARCHAR2(1),
    ERR_AGAMA                VARCHAR2(1),
    ERR_PENDIDIKAN           VARCHAR2(1),
    ERR_STATUS_KAWIN         VARCHAR2(1),
    ERR_STATUS_RUMAH         VARCHAR2(1),
    ERR_PEKERJAAN            VARCHAR2(1),
    ERR_KODE_PROFESI         VARCHAR2(1),
    ERR_STATUS_PEKERJAAN     VARCHAR2(1),
    ERR_HUBUNGAN             VARCHAR2(1),
    ERR_STATUS_INSTANSI      VARCHAR2(1),
    ERR_TANGGAL_LAHIR        VARCHAR2(1),
    ERR_NO_IDENTITAS         VARCHAR2(1),
    ERR_FINAL_INSERT         VARCHAR2(1),

    MSG_NAMA                 VARCHAR2(500),
    MSG_JEN_KELAMIN          VARCHAR2(500),
    MSG_KEBANGSAAN           VARCHAR2(500),
    MSG_AGAMA                VARCHAR2(500),
    MSG_PENDIDIKAN           VARCHAR2(500),
    MSG_STATUS_KAWIN         VARCHAR2(500),
    MSG_STATUS_RUMAH         VARCHAR2(500),
    MSG_PEKERJAAN            VARCHAR2(500),
    MSG_KODE_PROFESI         VARCHAR2(500),
    MSG_STATUS_PEKERJAAN     VARCHAR2(500),
    MSG_HUBUNGAN             VARCHAR2(500),
    MSG_STATUS_INSTANSI      VARCHAR2(500),
    MSG_TANGGAL_LAHIR        VARCHAR2(500),
    MSG_NO_IDENTITAS         VARCHAR2(500),
    MSG_FINAL_INSERT         VARCHAR2(1000),

    ERROR_COLUMNS            VARCHAR2(4000), -- daftar kolom yang gagal, dipisah koma
    CREATED_AT               TIMESTAMP,
    CREATED_BY               VARCHAR2(200),
    VALIDATED_AT             TIMESTAMP,
    LOADED_AT                TIMESTAMP,

    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_FK1 FOREIGN KEY (UPLOAD_BANSOS_ID) 
        REFERENCES BJKT_UPLOAD_BANSOS (ID) ON DELETE CASCADE,
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_FK2 FOREIGN KEY (PROGRAM_ID) 
        REFERENCES BJKT_MASTER_PROGRAMS (ID) ON DELETE CASCADE,
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_STG_C1 CHECK (STATUS IN ('PENDING','VALID','ERROR','LOADED','SKIPPED'))
);
/

CREATE INDEX BJKT_BANSOS_RECIPIENTS_STG_I1 ON BJKT_BANSOS_RECIPIENTS_STG (BATCH_ID, STATUS);
/
CREATE INDEX BJKT_BANSOS_RECIPIENTS_STG_I2 ON BJKT_BANSOS_RECIPIENTS_STG (BATCH_ID, LINE_NUMBER);
/
CREATE INDEX BJKT_BANSOS_RECIPIENTS_STG_I3 ON BJKT_BANSOS_RECIPIENTS_STG (PROGRAM_ID, STATUS);
/

CREATE SEQUENCE BJKT_BANSOS_RECIPIENTS_STG_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_BANSOS_RECIPIENTS_STG_TRG
BEFORE INSERT
ON BJKT_BANSOS_RECIPIENTS_STG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_BANSOS_RECIPIENTS_STG_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
   END
   CREATE TABLE TO STORE DATA STAGGING PENERIMA BANSOS
*/

/*
   START
   CREATE TABLE TO STORE DATA ERROR STAGGING PENERIMA BANSOS
*/
DROP TABLE BJKT_BANSOS_RECIPIENTS_ERR;
/

CREATE TABLE BJKT_BANSOS_RECIPIENTS_ERR (
    ID                      NUMBER NOT NULL,
    BATCH_ID                NUMBER NOT NULL,
    UPLOAD_BANSOS_ID        NUMBER NOT NULL,
    PROGRAM_ID              NUMBER NOT NULL,
    LINE_NUMBER             NUMBER,
    ERROR_SOURCE            VARCHAR2(20), -- 'VALIDATION' or 'FINAL_INSERT'

    NAMA                    VARCHAR2(500),
    NO_IDENTITAS            VARCHAR2(50),
    TANGGAL_LAHIR           VARCHAR2(50),
    JEN_KELAMIN             VARCHAR2(100),
    AGAMA                   VARCHAR2(100),
    PENDIDIKAN              VARCHAR2(100),
    STATUS_KAWIN            VARCHAR2(100),
    STATUS_RUMAH            VARCHAR2(100),
    PEKERJAAN_BIDANG_USAHA  VARCHAR2(200),
    KODE_PROFESI            VARCHAR2(100),
    STATUS_PEKERJAAN        VARCHAR2(100),
    HUBUNGAN                VARCHAR2(100),
    STATUS_INSTANSI         VARCHAR2(100),

    ERROR_COLUMNS           VARCHAR2(4000),
    ERROR_DETAILS_JSON      CLOB,             -- [{col:msg}, ...] per baris
    
    CREATED_AT              TIMESTAMP,
    CREATED_BY              VARCHAR2(200),

    CONSTRAINT BJKT_BANSOS_RECIPIENTS_ERR_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_ERR_FK1 FOREIGN KEY (UPLOAD_BANSOS_ID) 
        REFERENCES BJKT_UPLOAD_BANSOS (ID) ON DELETE CASCADE,
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_ERR_FK2 FOREIGN KEY (PROGRAM_ID) 
        REFERENCES BJKT_MASTER_PROGRAMS ON DELETE CASCADE,
    CONSTRAINT BJKT_BANSOS_RECIPIENTS_ERR_C1 CHECK (
        ERROR_DETAILS_JSON IS NULL
        OR ERROR_DETAILS_JSON LIKE '[%]'
    )
);
/

CREATE INDEX BJKT_BANSOS_RECIPIENTS_ERR_I1 ON BJKT_BANSOS_RECIPIENTS_ERR (BATCH_ID, ERROR_SOURCE);
/
CREATE INDEX BJKT_BANSOS_RECIPIENTS_ERR_I2 ON BJKT_BANSOS_RECIPIENTS_ERR (UPLOAD_BANSOS_ID);
/
CREATE INDEX BJKT_BANSOS_RECIPIENTS_ERR_I3 ON BJKT_BANSOS_RECIPIENTS_ERR (PROGRAM_ID, NO_IDENTITAS);
/

CREATE SEQUENCE BJKT_BANSOS_RECIPIENTS_ERR_S START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE OR REPLACE TRIGGER BJKT_BANSOS_RECIPIENTS_ERR_TRG
BEFORE INSERT ON BJKT_BANSOS_RECIPIENTS_ERR
FOR EACH ROW
BEGIN
    :NEW.ID         := NVL(:NEW.ID, BJKT_BANSOS_RECIPIENTS_ERR_S.NEXTVAL);
    :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
    :NEW.CREATED_AT := SYSTIMESTAMP;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
/*
   END
   CREATE TABLE TO STORE DATA ERROR STAGGING PENERIMA BANSOS
*/

/*
    -- START --
    CREATE TABLE TO STORE DATA PENERIMA BANSOS
*/
DROP TABLE BJKT_HISTORY_BANSOS_RECIPIENTS;
/

CREATE TABLE BJKT_HISTORY_BANSOS_RECIPIENTS (
    ID                          NUMBER NOT NULL,
    NAME                        VARCHAR2(255),
    GENDER_MASTER_CODE          VARCHAR2(255),
    NATIONALITY_MASTER_CODE     VARCHAR2(255),
    BORN_PLACE                  VARCHAR2(255),
    BORN_DATE                   DATE,
    IDENTITY_CARD_NUM           VARCHAR2(255),
    MOTHER_OR_GUARDIAN_NAME     VARCHAR2(255),
    RELIGION_MASTER_CODE        VARCHAR2(255),
    EDUCATION_MASTER_CODE       VARCHAR2(255),

    ID_CARD_ADDRESS         VARCHAR2(1000),
    DOMICILE_ADDRESS        VARCHAR2(1000),
    RT                      VARCHAR2(50),
    RW                      VARCHAR2(50),
    VILLAGE                 VARCHAR2(255),
    DISTRICT                VARCHAR2(255),
    CITY                    VARCHAR2(255),
    PROVINCE                VARCHAR2(255),
    POSTAL_CODE             VARCHAR2(50),
    PHONE_NUM               VARCHAR2(50),

    INSTITUTION_NUM                 VARCHAR2(200),
    INSTITUTION_NAME                VARCHAR2(255),
    INSTITUTION_ADDRESS             VARCHAR2(1000),
    INSTITUTION_POSTAL_CODE         VARCHAR2(50),
    INSTITUTION_PHONE_NUM           VARCHAR2(50),
    INTITUTION_TYPE_MASTER_CODE     VARCHAR2(200),

    CONTACT_PERSON_NAME             VARCHAR2(255),
    FAMILY_RELATIONSHIP_MASTER_CODE VARCHAR2(255),
    CONTACT_PERSON_ADDRESS          VARCHAR2(255),
    CONTACT_PERSON_CITY             VARCHAR2(255),
    CONTACT_PERSON_PROVINCE         VARCHAR2(255),
    CONTACT_PERSON_PHONE_NUM        VARCHAR2(50),

    MARRIAGE_STATUS_CODE            VARCHAR2(255),
    HOUSE_MASTER_STATUS_CODE        VARCHAR2(255),
    JOB_MASTER_CODE                 VARCHAR2(255),
    PROFESSION_MASTER_CODE          VARCHAR2(255),
    JOB_STATUS_MASTER_CODE          VARCHAR2(255),

    HUSBAND_WIFE                    VARCHAR2(255),

    PROCESS_STATUS_MASTER_CODE      VARCHAR2(255) DEFAULT '0',
    DISTRIBUTION_STATUS_MASTER_CODE VARCHAR2(255) DEFAULT '00',
    FUND_MASTER_STATUS_CODE         VARCHAR2(255) DEFAULT '3',
    ACCOUNT_MASTER_STATUS_CODE      VARCHAR2(255) DEFAULT '3',

    PROGRAM_MASTER_CODE             VARCHAR2(255),

    USER_APPROVER                   VARCHAR2(200),

    UPLOAD_CODE                     VARCHAR2(255),
    UPLOAD_DATE                     TIMESTAMP,

    /*
        VALIDATION FLAG:
        0 = Belum divalidasi
        1 = Valid
        2 = Tidak valid
    */
    VALIDATION_FLAG                 NUMBER(1) DEFAULT 0,
    VALIDATION_NOTES                CLOB,

    FUND_AMOUNT                     NUMBER,
    BANK_ACCOUNT_NUM                VARCHAR2(255),

    RECIPIENT_STATUS_MASTER_STATUS  VARCHAR2(255) DEFAULT '00',
    DEBIT_CARD_NUM                  VARCHAR2(255),

    DISTRIBUTION_MANAGER                VARCHAR2(255),
    DISTRIBUTION_PLACE                  VARCHAR2(1000),
    DEBIT_CREDIT_STATUS_MASTER_CODE     VARCHAR2(100),
    DISTRIBUTION_LOCATION_MASTER_CODE   VARCHAR2(200),

    PROCESS_DATE                    CLOB,

    ID_USER_REQUEST                 NUMBER DEFAULT 0,

    UPLOAD_DANA_IS_APPROVE          NUMBER(1) DEFAULT 0,
    TOTAL_DANA                      NUMBER,

    CREATED_BY                      VARCHAR2(200),
    CREATION_DATE                   TIMESTAMP,
    LAST_UPDATED_BY                 VARCHAR2(200),
    LAST_UPDATE_DATE                TIMESTAMP,

    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_PK PRIMARY KEY (ID),
    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_C1 CHECK (VALIDATION_FLAG IN (0, 1, 2)),
    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_C2 CHECK (VALIDATION_NOTES IS JSON),
    CONSTRAINT BJKT_HISTORY_BANSOS_RECIPIENTS_C3 CHECK (PROCESS_DATE IS JSON)
);
/

CREATE INDEX BJKT_HISTORY_BANSOS_RECIPIENTS_I1 ON BJKT_HISTORY_BANSOS_RECIPIENTS (PROGRAM_MASTER_CODE);
/
CREATE INDEX BJKT_HISTORY_BANSOS_RECIPIENTS_I2 ON BJKT_HISTORY_BANSOS_RECIPIENTS (PROGRAM_MASTER_CODE, IDENTITY_CARD_NUM);
/

CREATE SEQUENCE BJKT_HISTORY_BANSOS_RECIPIENTS_S
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BJKT_HISTORY_BANSOS_RECIPIENTS_TRG
BEFORE INSERT OR UPDATE
ON BJKT_HISTORY_BANSOS_RECIPIENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ID := NVL(:NEW.ID, BJKT_HISTORY_BANSOS_RECIPIENTS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
        :NEW.CREATION_DATE := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY := NVL(V('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
/*
    -- END --
    CREATE TABLE TO STORE DATA PENERIMA BANSOS
*/

/*
    -- START --
    CREATE TABLE VIEW TO CALCULATE DATA PENERIMA BANSOS
*/
CREATE OR REPLACE VIEW BJKT_CAL_BANSOS_RECIPIENTS_V AS
SELECT
    u.PROGRAM_ID,
    p.CODE,
    SUM(u.TOTAL_ROWS)              AS TOTAL_DATA,
    SUM(u.LOADED_ROWS)             AS TOTAL_VALID,
    NVL(MAX(e.TOTAL_ERR), 0)       AS TOTAL_INVALID
FROM BJKT_UPLOAD_BANSOS u
LEFT JOIN BJKT_MASTER_PROGRAMS p ON p.ID = u.PROGRAM_ID
LEFT JOIN (
    SELECT
        PROGRAM_ID,
        COUNT(*) AS TOTAL_ERR
    FROM  BJKT_BANSOS_RECIPIENTS_ERR
    GROUP BY PROGRAM_ID
) e ON e.PROGRAM_ID = u.PROGRAM_ID
WHERE u.PROGRAM_ID = (
    SELECT MAX(ID)
    FROM   BJKT_MASTER_PROGRAMS
    WHERE  STATUS_DATA = 1
)
  AND u.STATUS != 'PROCESSING'
GROUP BY u.PROGRAM_ID, p.CODE;
/
/*
    -- END --
    CREATE TABLE VIEW TO CALCULATE DATA PENERIMA BANSOS
*/