SELECT
    'TABUNGAN MONAS PEKERJA'    AS JENIS_REKENING,
    20923223274                 AS NOMOR_REKENING,
    'MAYASARI'                  AS PEMILIK_REKENING,
    'KANTOR CABANG PEMBANTU KAWASAN BERIKAT NUSANTARA' AS CABANG_TUJUAN,
    17000000                    AS NOMINAL_TRANSAKSI,
    0                           AS BIAYA_TRANSAKSI,
    1                           AS KURS,
    17000000                    AS TOTAL_TRANSAKSI,
    'SETOR TUNAI'               AS KETERANGAN,
    '108 KANTOR CABANG UTAMA BALAIKOTA' AS CABANG,
    '20-12-2024 / 17:02:32'     AS TANGGAL_TRANSAKSI,
    '1000 - SETOR TUNAI'        AS JENIS_TRANSAKSI,
    'IDR - RUPIAH'              AS MT_UANG_TRANSAKSI,
    'E2T7TW'                    AS KODE_REFERENSI,
    'AR39190319'                AS TELLER,
    NULL                        AS SUPERVISOR,
    'MAYASARI'                  AS NAMA_PENYETOR,
    'JALAN MANDALA 1 NO 19'     AS ALAMAT_PENYETOR,
    'KTP'                       AS JENIS_IDENTITAS,
    '3175105503900009'          AS NO_IDENTITAS,
    '089812121111'              AS NO_TELP,
    NULL                        AS SUMBER_DANA,
    NULL                        AS TUJUAN_TRANSAKSI
FROM DUAL;