SET DEFINE OFF;
/
/*
    START - INSERT HUBUNGAN KELUARGA
*/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('A', 'Orang Tua Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('B', 'Saudara Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('C', 'Suami/Istri');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('D', 'Kakak');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('E', 'Suami/Istri Dari Anak Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('F', 'Kakek/Nenek Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('G', 'Cucu Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('H', 'Saudara Kandung/Tiri/Angkat Dari Suami/Istri');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('I', 'Suami/Istri Dari Saudara Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('J', 'Saudara Kandung/Tiri/Angkat Dari Orang Tua');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('K', 'Anak Kandung/Tiri/Angkat');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('L', 'Mertua');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('Y', 'SKPD Pemilik Program');
/
INSERT INTO BJKT_BANSOS_MASTER_HUB_KELUARGA (KODE, DESKRIPSI)
VALUES ('Z', 'Lain-Lain');
/
/*
    END - INSERT HUBUNGAN KELUARGA
*/

/*
    START - INSERT PEKERJAAN
*/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('A', 'Pertanian');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('B', 'Pertambangan');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('C', 'Industri Pengolahan');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('D', 'Listrik, Gas dan Air');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('E', 'Konstruksi');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('F', 'Perdagangan, Restoran dan Hotel');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('G', 'Pengangkutan, Pergudangan dan Komunikasi');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('H', 'Jasa-jasa Dunia');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('I', 'Jasa-jasa Sosial/Masyarakat');
/
INSERT INTO BJKT_BANSOS_MASTER_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('J', 'Lainnya');
/
/*
    END - INSERT PEKERJAAN
*/

/*
    START - INSERT PENDIDIKAN
*/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('00', 'Tanpa Gelar');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('01', 'Diploma 1');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('02', 'Diploma 2');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('03', 'Diploma 3');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('04', 'S1');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('05', 'S2');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('06', 'S3');
/
INSERT INTO BJKT_BANSOS_MASTER_PENDIDIKAN (KODE, DESKRIPSI)
VALUES ('99', 'Lainnya');
/
/*
    END - INSERT PENDIDIKAN
*/

/*
    START - INSERT PROFESI
*/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('1', 'Accounting/Finance Officer');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('2', 'Customer Service');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('3', 'Engineering');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('4', 'Eksekutif');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('5', 'Administrasi umum');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('6', 'Teknologi informasi');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('7', 'Konsultan/Analis');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('8', 'Marketing');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('9', 'Pengajar (Guru,Dosen)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('10', 'Militer');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('11', 'Pensiunan');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('12', 'Pelajar/Mahasiswa');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('13', 'Wiraswasta');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('14', 'Polisi');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('15', 'Petani');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('16', 'Nelayan');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('17', 'Peternak');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('18', 'Dokter');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('19', 'Tenaga Medis (Perawat, Bidan, dan sebagainya)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('20', 'Hukum (Pengacara, Notaris)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('21', 'Perhotelan & restoran (Koki,Bartender, dsb)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('22', 'Peneliti');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('23', 'Desainer');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('24', 'Arsitek');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('25', 'Pekerja seni (artis, musisi, pelukis, dsb)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('26', 'Pengamanan');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('27', 'Pialang/Broker');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('28', 'Distributor');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('29', 'Transportasi udara (pilot, pramugari)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('30', 'Transportasi laut (nahkoda, anak buah kapal)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('31', 'Transportasi darat (masinis, sopir,kondektur)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('32', 'Buruh (buruh pabrik,buruh bangunan,buruhtani)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('33', 'Pertukangan & Pengrajin (tukangkayu,pengrajin)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('34', 'Ibu rumah tangga');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('35', 'Pekerja informal (asisten rumatangga,asongan)');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('36', 'Pejabat negara/penyelenggara negara');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('37', 'Pegawai pemerintahan/lembaga negara');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('98', 'Penerima Program Pemprov DKI');
/
INSERT INTO BJKT_BANSOS_MASTER_PROFESI (KODE, DESKRIPSI)
VALUES ('99', 'Lain-Lain');
/
/*
    END - INSERT PROFESI
*/

/*
    START - INSERT STATUS KAWIN
*/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_KAWIN (KODE, DESKRIPSI)
VALUES ('B', 'Belum Menikah');
/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_KAWIN (KODE, DESKRIPSI)
VALUES ('D', 'Cerai');
/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_KAWIN (KODE, DESKRIPSI)
VALUES ('K', 'Kawin');
/
/*
    END - INSERT STATUS KAWIN
*/

/*
    START - INSERT STATUS PEKERJAAN
*/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('1', 'Tetap');
/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('2', 'Kontrak');
/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('3', 'Honorer');
/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('4', 'Tidak Kerja');
/
INSERT INTO BJKT_BANSOS_MASTER_STATUS_PEKERJAAN (KODE, DESKRIPSI)
VALUES ('8', 'Program Pemprov DKI');
/
/*
    END - INSERT STATUS PEKERJAAN
*/

/*
    START - INSERT JENIS INSTANSI
*/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('00', 'SD');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('01', 'SMP');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('02', 'SMA');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('03', 'D3');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('04', 'S1');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('05', 'S2');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('06', 'S3');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('99', 'Tidak terdefinisi');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('07', 'D4 Test');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('22', 'KEJAR PAKET C');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('15', 'Kejar Paket A');
/
INSERT INTO BJKT_BANSOS_MASTER_JENIS_INSTANSI (KODE, DESKRIPSI)
VALUES ('08', 'KEJAR PAKET B');
/
/*
    END - INSERT 
*/
COMMIT;
/